apiVersion: v1
kind: Service
metadata:
  name: img-pull-secret-demo-svc
spec:
  selector:
    app: img-pull-secret-demo
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: img-pull-secret-demo
  labels:
    app: img-pull-secret-demo
    app.kubernetes.io/name: img-pull-secret-demo
    app.kubernetes.io/version: "0.1"
spec:
  containers:
  - name: img-pull-secret-demo
    image: datadaddy/react-demo:0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred    

