apiVersion: v1
kind: Service
metadata:
  name: demo-webapp-service
spec:
  selector:
    app: service-demo-app
    app.kubernetes.io/name: service-demo-app
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP  # Not really necessary, this is the default