apiVersion: batch/v1
kind: Job
metadata:
  name: lottery-job
spec:
  completions: 7
  template:
    spec:
      containers:
      - name: lottery-job
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["echo Tonights lottery number: `od -vAn -N2 -tu2 < /dev/urandom`"]
      restartPolicy: Never
