apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvol000-pv-claim
spec:
  storageClassName: pvol000-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
